### ISSUE TITLE
parse_hl7_message results in error

### ISSUE THREAD

**Issue by venkyvb** [databrickslabs/smolder#12]
Hi, I am trying to parse HL7 message using the `parse_hl7_message` function (similar to the example in the doc)
```
val parsedDf = hl7Bronze.select(parse_hl7_message($"value").as("message"))
```
 and I am getting the following error. Any hints as to what could be going wrong? Thanks a lot !

```
java.lang.AbstractMethodError: Method com/databricks/labs/smolder/sql/ParseHL7Message.child()Lorg/apache/spark/sql/catalyst/trees/TreeNode; is abstract
  at com.databricks.labs.smolder.sql.ParseHL7Message.child(ParseHL7Message.scala)

  at org.apache.spark.sql.catalyst.trees.UnaryLike.children(TreeNode.scala:1127)

  at org.apache.spark.sql.catalyst.trees.UnaryLike.children$(TreeNode.scala:1127)

  at org.apache.spark.sql.catalyst.expressions.UnaryExpression.children$lzycompute(Expression.scala:467)

  at org.apache.spark.sql.catalyst.expressions.UnaryExpression.children(Expression.scala:467)

  at org.apache.spark.sql.catalyst.trees.TreeNode.getDefaultTreePatternBits(TreeNode.scala:119)

  at org.apache.spark.sql.catalyst.trees.TreeNode.treePatternBits$lzycompute(TreeNode.scala:130)

  at org.apache.spark.sql.catalyst.trees.TreeNode.treePatternBits(TreeNode.scala:130)

  at org.apache.spark.sql.catalyst.trees.TreeNode.getDefaultTreePatternBits(TreeNode.scala:121)

  at org.apache.spark.sql.catalyst.trees.TreeNode.treePatternBits$lzycompute(TreeNode.scala:130)

  at org.apache.spark.sql.catalyst.trees.TreeNode.treePatternBits(TreeNode.scala:130)

  at org.apache.spark.sql.catalyst.plans.QueryPlan.treePatternBits$lzycompute(QueryPlan.scala:62)

  at org.apache.spark.sql.catalyst.plans.QueryPlan.treePatternBits(QueryPlan.scala:57)

  at org.apache.spark.sql.catalyst.trees.TreePatternBits.containsPattern(TreePatternBits.scala:32)

  at org.apache.spark.sql.catalyst.trees.TreePatternBits.containsPattern$(TreePatternBits.scala:31)

  at org.apache.spark.sql.catalyst.trees.TreeNode.containsPattern(TreeNode.scala:96)

  at org.apache.spark.sql.catalyst.optimizer.OptimizeUpdateFields$.$anonfun$apply$1(UpdateFields.scala:76)

  at org.apache.spark.sql.catalyst.optimizer.OptimizeUpdateFields$.$anonfun$apply$1$adapted(UpdateFields.scala:76)

  at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsDownWithPruning(AnalysisHelper.scala:167)

  at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsDownWithPruning$(AnalysisHelper.scala:164)

  at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperatorsDownWithPruning(LogicalPlan.scala:30)

  at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsWithPruning(AnalysisHelper.scala:99)

  at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsWithPruning$(AnalysisHelper.scala:96)

  at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperatorsWithPruning(LogicalPlan.scala:30)

  at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveExpressionsWithPruning(AnalysisHelper.scala:244)

  at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveExpressionsWithPruning$(AnalysisHelper.scala:242)

  at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveExpressionsWithPruning(LogicalPlan.scala:30)

  at org.apache.spark.sql.catalyst.optimizer.OptimizeUpdateFields$.apply(UpdateFields.scala:76)

  at org.apache.spark.sql.catalyst.optimizer.OptimizeUpdateFields$.apply(UpdateFields.scala:33)

  at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$2(RuleExecutor.scala:211)

  at scala.collection.IndexedSeqOptimized.foldLeft(IndexedSeqOptimized.scala:60)

  at scala.collection.IndexedSeqOptimized.foldLeft$(IndexedSeqOptimized.scala:68)

  at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:38)

  at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1(RuleExecutor.scala:208)

  at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1$adapted(RuleExecutor.scala:200)

  at scala.collection.immutable.List.foreach(List.scala:431)

  at org.apache.spark.sql.catalyst.rules.RuleExecutor.execute(RuleExecutor.scala:200)

  at org.apache.spark.sql.catalyst.analysis.Analyzer.org$apache$spark$sql$catalyst$analysis$Analyzer$$executeSameContext(Analyzer.scala:222)

  at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$execute$1(Analyzer.scala:218)

  at org.apache.spark.sql.catalyst.analysis.AnalysisContext$.withNewAnalysisContext(Analyzer.scala:167)

  at org.apache.spark.sql.catalyst.analysis.Analyzer.execute(Analyzer.scala:218)

  at org.apache.spark.sql.catalyst.analysis.Analyzer.execute(Analyzer.scala:182)

  at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$executeAndTrack$1(RuleExecutor.scala:179)

  at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:93)

  at org.apache.spark.sql.catalyst.rules.RuleExecutor.executeAndTrack(RuleExecutor.scala:179)

  at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$executeAndCheck$1(Analyzer.scala:203)

  at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.markInAnalyzer(AnalysisHelper.scala:330)

  at org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:202)

  at org.apache.spark.sql.execution.QueryExecution.$anonfun$analyzed$1(QueryExecution.scala:78)

  at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:120)

  at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:207)

  at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)

  at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:207)

  at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:78)

  at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:76)

  at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:68)

  at org.apache.spark.sql.Dataset$.$anonfun$ofRows$1(Dataset.scala:91)

  at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)

  at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:89)

  at org.apache.spark.sql.Dataset.withPlan(Dataset.scala:3747)

  at org.apache.spark.sql.Dataset.select(Dataset.scala:1467)
```

**Comment by venkyvb** [comment]
Did some further investigation, the issue is with Spark 3.2.0. When I use Spark 3.1.0 with scala 2.12.8 it works fine. With Spark 3.2.0 during compile stage the following error happens:

```
[info] Compiling 5 Scala sources to C:\Users\venkib\projects\smolder\target\scala-2.12\classes ...
[error] C:\Users\venkib\projects\smolder\src\main\scala\com\databricks\labs\smolder\sql\ParseHL7Message.scala:24:29: class ParseHL7Message needs to be abstract, since method withNewChildInternal in trait UnaryLike of type (newChild: org.apache.spark.sql.catalyst.expressions.Expression)org.apache.spark.sql.catalyst.expressions.Expression is not defined
[error] private[smolder] case class ParseHL7Message(child: Expression)                                                                                                 
[error]                             ^                                                                                                                                  
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 7 s, completed Oct 15, 2022, 5:32:36 PM
```

**Comment by gxlau** [comment]
I can run in  spark 3.2+ but had to modify the ParseHL7Message.scala class, in the class I added the following:
` override protected def withNewChildInternal(newChild: Expression): Expression = copy(child = newChild)`

**Comment by venkyvb** [comment]
Issue fixed with https://github.com/databrickslabs/smolder/pull/14
